language: php

dist: xenial

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  - COMPOSER_NO_INTERACTION=1

matrix:
  include:
    - php: 7.3
      env:
        - COMPOSER_NO_INTERACTION=1
        - PHPSTAN_VERSION=0.11.19
    - php: 7.4
      env:
        - COMPOSER_NO_INTERACTION=1
        - PHPSTAN_VERSION=0.11.19
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - "$HOME/.composer/cache"

install:
  - travis_retry composer install --no-scripts --no-suggest

before_script:
  - |
    if [ -n "${PHPSTAN_VERSION}" ]; then
        composer require "phpstan/phpstan:${PHPSTAN_VERSION}"
        vendor/bin/phpstan analyse --no-progress
    fi

script:
  - composer validate --strict
  - find src/ examples/ tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 php -l
  - vendor/bin/phpunit

before_deploy:
  - sed -e "/const CLIENT_VERSION/c\\    const CLIENT_VERSION = '${TRAVIS_TAG:1}';" -i src/MollieApiClient.php
  - make mollie-api-php.zip

deploy:
  provider: releases
  api_key:
    secure: oXVzXjLkVfr7+5leMbIHQnLDg1o9/ldG6qdJ/GtwumZJYiit9h7VBYpxRvQGgXUESzhDlBf2jCLKxqxW+P2/PwG738/rSJVjLvbtbyFRz+pvk4o8rm3U7IKRv87BFhIvhaO9HcgvmyHbPMzGKRdAsWYWGQf/dg9N77xeDZ9++80=
  file: mollie-api-php.zip
  skip_cleanup: true
  on:
    tags: true
    php: 7.2
