language: php

php:
- 5.3
- 5.4
- 5.5
- 5.5.9
- 5.6
- 7.0
- 7.1
- hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction

script:
- vendor/bin/phpunit
